CIFAR10_CLASSES:
  - airplane
  - automobile
  - bird
  - cat
  - deer
  - dog
  - frog
  - horse
  - ship
  - truck

ANIMACY:
  airplane: inanimate
  automobile: inanimate
  ship: inanimate
  truck: inanimate
  bird: animate
  cat: animate
  deer: animate
  dog: animate
  frog: animate
  horse: animate

ANIMACY_MAPPING:
  animate: 0
  inanimate: 1